name: make-dependencies

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run Makefile Deps
      run: sudo make deps
